// ==UserScript==
// @name         Myko.cz – atlas na mobilu
// @namespace    urn:myko-cz-responsive
// @version      0.0.1
// @description  Čitelný atlas hub na telefonu: fotografie, hledání a navigace.
// @author       Myko.cz Responsive contributors
// @license      EUPL-1.2
// @homepageURL  https://github.com/brozkeff/myko-cz-responsive
// @supportURL   https://github.com/brozkeff/myko-cz-responsive/issues
// @match        *://myko.cz/myko-atlas/*
// @match        *://www.myko.cz/myko-atlas/*
// @run-at       document-end
// @grant        none
// @noframes
// ==/UserScript==

/* Copyright (c) 2026 Myko.cz Responsive contributors
 * SPDX-License-Identifier: EUPL-1.2
 * License text: https://github.com/brozkeff/myko-cz-responsive/blob/v0.0.1/LICENSE
 * Original myko.cz content belongs to its respective authors.
 */
(() => {
  'use strict';
  if (!['myko.cz', 'www.myko.cz'].includes(location.hostname)
      || !location.pathname.startsWith('/myko-atlas/')) return;
  const content = document.querySelector('#content');
  if (!content || document.querySelector('#myko-responsive-style')) return;

  const viewport = document.querySelector('meta[name="viewport"]') || document.createElement('meta');
  viewport.name = 'viewport';
  viewport.content = 'width=device-width, initial-scale=1';
  document.head.append(viewport);
  const style = document.createElement('style');
  style.id = 'myko-responsive-style';
  // CSS-BEGIN (generated by build.mjs)
  style.textContent = "/* Copyright (c) 2026 Myko.cz Responsive contributors\n * SPDX-License-Identifier: EUPL-1.2\n * Version: 0.0.1. Original myko.cz content belongs to its respective authors.\n */\n.myko-mobile-tools, .myko-menu-toggle, .myko-edibility { display: none; }\n\n@media screen and (max-width: 1000px) {\n  html { scroll-padding-top: 1rem; }\n  body.myko { margin: 0; background: #e8eee6; }\n  #main, #footer { width: 100%; max-width: 100%; }\n  #main, #main *, #footer { box-sizing: border-box; }\n  #leftcol, #centercol, #rightcol { float: none; width: 100%; margin: 0; }\n  #lefthdr, #menulista, #centerhdr, #pravalista, .menustin, .hlavnistin,\n  #sponzori, #counter { display: none; }\n  #menu { display: none; }\n  #menu.myko-menu-open { display: block; }\n  #menu a { width: auto; min-height: 44px; padding: 12px; }\n  #centerlista { height: auto; background: #0b683c; padding: 12px; }\n  #centerlista h1 { padding: 0; font-size: 1.25rem; overflow-wrap: anywhere; }\n  #navigace { padding: 10px 12px; text-align: left; line-height: 1.6; }\n  #content { min-height: 0; padding: 12px; font-size: 18px; line-height: 1.6; background: #fff; overflow-wrap: anywhere; }\n  #content h2, #content h3, #content p { margin: 0 0 12px; padding: 0; text-align: left; white-space: normal; }\n  #content h2 { font-size: 1.4em; }\n  #content h3 { font-size: 1.15em; padding-top: 12px; }\n  #content ul, #content ol, #content blockquote { margin: 0 0 12px; padding: 0 0 0 24px; text-align: left; }\n  #content a, #content a em, #content a strong, #navigace a { color: #8c3b0c; }\n  #content p > a:only-child, #content h2 > a { display: inline-block; padding: 8px 4px; min-height: 44px; }\n  #content div.right, #content div.left, #content div.leftfirst { float: none; margin: 12px 0; max-width: 100%; }\n  #content img { max-width: 100%; height: auto; }\n  #content .imgwrap { width: auto !important; height: auto !important; max-width: 100%; background: none; }\n  #content img.icon { max-width: none; vertical-align: middle; }\n  #content table { width: 100%; max-width: 100%; margin: 12px 0; font-size: inherit; table-layout: fixed; }\n  #content table.atlas, #content table.atlaslist { width: 100%; margin: 12px 0; }\n  #content table.atlaslist td { min-width: 0; }\n  #content table td, #content table th { min-width: 0; width: auto; white-space: normal; padding: 4px; }\n  #content table.atlas td[width], #content table.atlas th[width] { width: auto; }\n  #content .myko-gallery, #content .myko-gallery tbody { display: block; }\n  #content .myko-gallery tbody { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }\n  #content .myko-gallery tr { display: contents; }\n  #content .myko-gallery td, #content .myko-gallery th { display: block; padding: 0; }\n  #content .myko-gallery .myko-empty { display: none; }\n  #content .myko-gallery img { display: block; width: 100%; height: auto; }\n  #content button, #content input, #content select, #content textarea { font: inherit; max-width: 100%; }\n  #content button.atlasmenu, #content button.adminmenu { width: 100%; margin: 4px 0; padding: 10px; min-height: 44px; }\n  #content fieldset, #content fieldset.atlasmenu { min-width: 0; width: auto; margin: 8px 0; padding: 10px; }\n  #content input[name=\"searchtext\"] { width: 100% !important; margin: 0 !important; min-height: 44px; }\n  #content legend.atlasmenu { width: auto; max-width: 100%; }\n  #content iframe { max-width: 100%; }\n  .myko-menu-toggle { display: block; width: 100%; padding: 12px; min-height: 44px; font: inherit; background: #fff; color: #0b683c; border: 1px solid #0b683c; }\n  #content .myko-mobile-tools { display: block; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 1px solid #a9b7a5; }\n  #content .myko-edibility { display: inline; margin-left: 8px; font-weight: bold; }\n  #content h3 > a:has(img.icon) { display: inline-block; min-width: 44px; min-height: 44px; padding: 8px; }\n  #content .myko-mobile-tools nav { display: flex; flex-wrap: wrap; gap: 4px 12px; margin-bottom: 8px; }\n  #content .myko-mobile-tools a { display: inline-flex; align-items: center; min-height: 44px; padding: 4px; }\n  #content .myko-mobile-tools form { display: flex; flex-wrap: wrap; gap: 8px; }\n  #content .myko-mobile-tools label { width: 100%; }\n  #content .myko-mobile-tools input { flex: 1; min-width: 0; width: auto !important; padding: 8px; border: 1px solid #52694a; }\n  #content .myko-mobile-tools button { min-height: 44px; padding: 8px 12px; background: #0b683c; color: #fff; border: 0; }\n  #content :focus-visible, .myko-menu-toggle:focus-visible { outline: 3px solid #1d65ad; outline-offset: 2px; }\n  #rightcol { margin-top: 16px; }\n  #righthdr { width: 100%; height: auto; padding-bottom: 10px; }\n  #righthdr fieldset { width: 100%; }\n  #righthdr table { width: 100%; }\n  #righthdr input { max-width: 100%; }\n  #footer { height: auto; padding: 8px 12px; line-height: 1.6; }\n  .lightbox { max-width: 100%; }\n  .lb-outerContainer, .lb-dataContainer { max-width: 100%; }\n  .lightbox .lb-image { max-width: 100%; height: auto !important; }\n  .lb-nav a.lb-prev, .lb-nav a.lb-next, .lb-data .lb-close { opacity: 1; }\n}\n\n@media screen and (max-width: 359px) {\n  #content .myko-gallery tbody { grid-template-columns: minmax(0, 1fr); }\n}\n";
  // CSS-END
  document.head.append(style);

  // ponytail: classify static atlas tables once; revisit if the site loads them dynamically.
  for (const table of content.querySelectorAll('table.atlas, table.atlaslist')) {
    const cells = Array.from(table.querySelectorAll('td, th'));
    if (!table.querySelector('.imgwrap') || !cells.every(cell =>
      cell.querySelector('.imgwrap') || (!cell.textContent.trim() && !cell.querySelector('img, input, button, a')))) continue;
    table.classList.add('myko-gallery');
    for (const cell of cells) {
      if (!cell.querySelector('.imgwrap')) cell.classList.add('myko-empty');
    }
  }

  const tools = document.createElement('section');
  tools.className = 'myko-mobile-tools';
  tools.setAttribute('aria-label', 'Navigace a hledání v atlasu');
  tools.innerHTML = `<nav aria-label="Atlas hub">
    <a href="/myko-atlas/">Atlas hub</a>
    <a href="/myko-atlas/abecedni-atlas/">Abecedně</a>
    <a href="/myko-atlas/systematicky-atlas/">Systematika</a>
    </nav><form action="/myko-atlas/" method="get">
    <label for="myko-mobile-search">Hledat houbu (aspoň 3 znaky)</label>
    <input id="myko-mobile-search" name="searchtext" type="search" minlength="3" required placeholder="Český nebo latinský název">
    <button type="submit">Hledat</button></form>`;
  // The server renders its Windows-1250 query correctly; URLSearchParams assumes UTF-8.
  tools.querySelector('input').value = content.querySelector('input[name="searchtext"]')?.value
    || new URLSearchParams(location.search).get('searchtext') || '';
  const sections = document.createElement('nav');
  sections.setAttribute('aria-label', 'Části stránky');
  content.querySelectorAll('h3').forEach((heading, index) => {
    if (!['Systematika', 'Popis', 'Výskyt', 'Možná záměna', 'Kuchyňské využití', 'Druhy', 'Literatura', 'Nálezy'].includes(heading.textContent.trim())) return;
    if (!heading.id) heading.id = `myko-section-${index}`;
    const link = document.createElement('a');
    link.href = `#${heading.id}`;
    link.textContent = heading.textContent.trim();
    sections.append(link);
  });
  if (sections.childElementCount) tools.append(sections);
  content.prepend(tools);

  // Icon tooltips carry edibility information otherwise unavailable to touch users.
  for (const icon of content.querySelectorAll('img.icon[src*="/mykoatlas/"][title]')) {
    const label = document.createElement('span');
    label.className = 'myko-edibility';
    label.textContent = icon.title;
    icon.after(label);
  }
  const menu = document.querySelector('#menu');
  if (menu) {
    const toggle = document.createElement('button');
    toggle.className = 'myko-menu-toggle';
    toggle.type = 'button';
    toggle.textContent = 'Menu webu ČMS';
    toggle.setAttribute('aria-controls', 'menu');
    toggle.setAttribute('aria-expanded', 'false');
    toggle.addEventListener('click', () => {
      toggle.setAttribute('aria-expanded', String(menu.classList.toggle('myko-menu-open')));
    });
    menu.before(toggle);
  }
})();
